---
name: Validate Go code formatting

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main, master]
    paths:
      - "**.go"
      - ".github/workflows/format-go.yaml"
  pull_request:
    branches: [main, master]
    paths:
      - "**.go"
      - ".github/workflows/format-go.yaml"


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Ref: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions:
  contents: read

jobs:

  validateCodeFormatGo:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "src/gabo/go.mod"

      # Ref: https://github.com/actions/cache/blob/main/examples.md#go---modules
      # Warning: This is Linux specific
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Validate code formatting
        run: |
          gofmt -l .
          test -z "$(gofmt -l .)"
