---
# Run this locally with act - https://github.com/nektos/act
# act -j lintYaml
name: Lint YAML

on:  # yamllint disable-line rule:truthy
  push:
    branches: [master, main]
    paths:
      - '**.yml'
      - '**.yaml'
      - '.github/workflows/**.yml'
      - '.github/workflows/**.yaml'
  pull_request:
    branches: [master, main]
    paths:
      - '**.yml'
      - '**.yaml'
      - '.github/workflows/**.yml'
      - '.github/workflows/**.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lintYaml:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            "./**.yml"
            "./**.yaml"
            ".github/workflows/"

      - name: Check YAML files with linter
        uses: ibiqlik/action-yamllint@v3
        with:
          # All files under base dir
          file_or_dir: "."
          config_data: |
            extends: default
            yaml-files:
              - '*.yaml'
              - '*.yml'
            rules:
              document-start:
                level: warning
              line-length:
                level: warning
              new-line-at-end-of-file:
                level: warning
              trailing-spaces:
                level: warning
      - name: Lint GitHub Actions
        uses: reviewdog/action-actionlint@v1
      - name: Check GitHub Actions with 'actionlint'
        # Ref: https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions
        # shellcheck is too noisy and disabled
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color -shellcheck=
        shell: bash
