---
# Run this locally with act - https://github.com/nektos/act
# act -j lintGitHubActions
name: Lint GitHub Actions

on:  # yamllint disable-line rule:truthy
  push:
    branches: [master, main]
    paths:
      - ".github/workflows/**.yml"
      - ".github/workflows/**.yaml"
      - "src/gabo/internal/generator/data/*.yml"
      - "src/gabo/internal/generator/data/*.yaml"
  pull_request:
    branches: [master, main]
    paths:
      - ".github/workflows/**.yml"
      - ".github/workflows/**.yaml"
      - "src/gabo/internal/generator/data/*.yml"
      - "src/gabo/internal/generator/data/*.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Ref: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions:
  contents: read

jobs:
  lintGitHubActionsWithActionLint:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          sparse-checkout: |
            .github/workflows
            src/gabo/internal/generator/data
          sparse-checkout-cone-mode: false

      - name: Lint GitHub Actions
        uses: reviewdog/action-actionlint@a5524e1c19e62881d79c1f1b9b6f09f16356e281  # v1.65.2

      - name: Check GitHub Actions with 'actionlint'
        # Ref: https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions
        # shellcheck is too noisy and disabled
        run: |
          find .github/workflows -type f -print0 | xargs -0 -n1 -I % sh -c 'docker run --init --rm --network none -v "$PWD":/work:ro rhysd/actionlint:latest -shellcheck= /work/%'
          find src/gabo/internal/generator/data -type f -print0 | xargs -0 -n1 -I % sh -c 'docker run --init --rm --network none -v "$PWD":/work:ro rhysd/actionlint:latest -shellcheck= /work/%'
        shell: bash


  lintGitHubActionsForSecurity:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      security-events: write
      contents: read
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          sparse-checkout: |
            .github/workflows
            src/gabo/internal/generator/data
          sparse-checkout-cone-mode: false

      - name: Run zizmor on GitHub Actions
        run: docker run --rm --network none -v "$PWD":/work:ro  ghcr.io/woodruffw/zizmor:latest --offline /work/.github/workflows

      - name: Run zizmor on gabo's internal generator data
        run: find src/gabo/internal/generator/data -type f -print0 | xargs -0 -n1 -I % sh -c 'docker run --rm --network none -v "$PWD":/work:ro  ghcr.io/woodruffw/zizmor:latest --offline /work/%'
