# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
name: Release Go binaries with Go Releaser

on:
  push:
    # run only against tags
    tags:
      - '*'
  # For testing
  pull_request:
    branches: [main, master]

permissions:
  contents: write

jobs:

  releaseBinary:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch git tags
        run: git fetch --force --tags

      - uses: actions/setup-go@v4
        with:
          go-version: stable

      # More assembly might be required: Docker logins, GPG, etc. It all depends
      # on your needs.
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
